
-- Удаление таблиц, если они существуют
DROP TABLE IF EXISTS employee_project CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS timesheet CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Создание таблицы Employee
CREATE TABLE employee (
                          employee_id SERIAL PRIMARY KEY,
                          employee_name VARCHAR(100)
);

-- Создание таблицы Project
CREATE TABLE project (
                         project_id SERIAL PRIMARY KEY,
                         project_name VARCHAR(100)
);
-- Создание таблицы Employee_Project для связи Employee и Project
CREATE TABLE employee_project (
                                  employee_project_id SERIAL PRIMARY KEY,
                                  employee_id INT,
                                  project_id INT,
                                  FOREIGN KEY (employee_id) REFERENCES Employee(employee_id),
                                  FOREIGN KEY (project_id) REFERENCES Project(project_id)
);

-- Создание таблицы Timesheet
CREATE TABLE timesheet (
                           timesheet_id SERIAL PRIMARY KEY,
                           timesheet_project_id BIGINT,
                           timesheet_employee_id BIGINT,
                           minutes INTEGER,
                           created_at DATE
);




-- Создание таблицы Roles
CREATE TABLE roles (
                       role_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       role_name VARCHAR(255) UNIQUE NOT NULL
);

-- Создание таблицы Users
CREATE TABLE users (
                       user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       login VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL
);



-- Создание таблицы User_Roles
CREATE TABLE user_roles (
                            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            FOREIGN KEY (user_id) REFERENCES users(user_id),
                            FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

-- -- Создание таблицы users
-- CREATE TABLE users (
--                        id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--                        login VARCHAR(255) UNIQUE NOT NULL,
--                        password VARCHAR(255) NOT NULL
-- );



--CREATE TABLE timesheet (
--                         timesheet_id SERIAL PRIMARY KEY,
--                         project_id INT,
--                         minutes INT
--);